#ci.gocd.yaml
environments:
 someshit:
   pipelines:
    - wp_mvn_docker
pipelines:
  wp_mvn_docker:
    group: Workbench_Deployments
    label_template: "${gitTdawg[:7]}"
    locking: off
    materials:
      workbench_wordpress: 
        git: http://github.com/sovrn/sovrn-workbench-wordpress.git
        branch: master
    stages:
      - Tdawg1.Build: # name of stage
          clean_workspace: true
          jobs:
            build: # name of the job
              resources:
               - nimbus2000
              artifacts:
               - build:
                   source: target
                   destination: build
              tasks:
               - exec: # indicates type of task
                   command: mvn
                   arguments:
                    - clean
                    - install
