#ci.gocd.yaml
environments:
 someshit:
   pipelines:
    - wp_mvn_docker
pipelines:
  wp_mvn_docker:
    group: Workbench_Deployments
    label_template: "${gitTdawg[:7]}"
    locking: off
    materials:
      workbench_wordpress: 
        git: git@github.com:sovrn/sovrn-workbench-wordpress.git
        branch: master
    stages:
      - build: 
        clean_workspace: true
        jobs:
          create_docker_mvn_image:
            resources:
              - docker
            tasks: 
              - exec:
                command: ls
                arguments:
