#ci.gocd.yaml
environments:
 workbench_deployment:
   pipelines:
    - wp_mvn_docker
pipelines:
  wp_mvn_docker:
    group: Workbench_Deployments
    label_template: "${COUNT}"
    locking: off
    materials:
      build: 
        git: git@github.com:sovrn/sovrn-workbench-wordpress.git
        branch: master
    stages:
      - mvn_image: # name of stage
          clean_workspace: true
          jobs:
            create_docker_mvn_image: # name of the job
              resources:
               - docker
              tasks:
               - exec: # indicates type of task
                   command: mvn
                   arguments:
                    - '-v'
