#tdawg.gocd.yaml
environments:
 Tdawg.Env:
   pipelines:
    - Tdawg1
    - Tdawg2
    - Tdawg3
    - Tdawg4 # Adding comment
pipelines:
  Tdawg1: # definition of mypipe1 pipeline
    group: Tdawg.Group # note that the group name can contain only of alphanumeric & underscore characters
    label_template: "${gitTdawg[:7]}"
    locking: off
    materials:
      gitTdawg: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: http://github.com/kevinKalmbach/sovrnTest.git
        branch: master
    stages: # list of stages in order
      - Tdawg1.Build: # name of stage
          clean_workspace: true
          jobs:
            build: # name of the job
              resources:
               - nimbus2000
              artifacts:
               - build:
                   source: target
                   destination: build
              tasks:
               - exec: # indicates type of task
                   command: mvn
                   arguments:
                    - clean
                    - install
      - Tdawg1.Install: # name of stage
          clean_workspace: true
          jobs:
            install: # name of the job
              resources:
               - nimbus2000
              tasks:
               - fetch: # indicates type of task
                   pipeline: Tdawg1
                   stage: Tdawg1.Build
                   job: build
                   source: build/target
                   destination: 
