#tdawg.gocd.yaml
pipelines:
  Tdawg2: # definition of mypipe1 pipeline
    group: Tdawgs # note that the group name can contain only of alphanumeric & underscore characters
    label_template: "${gitTdawg[:7]}"
    locking: off
    environment_variables:
      COMPONENT: tdawg_product
      BRANCH: master
    materials:
      gitTdawg: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: http://github.com/kevinKalmbach/sovrnTest.git
        branch: 
    stages: # list of stages in order
      - Tdawg2.Build: # name of stage
          fetch_materials: yes
          keep_artifacts: yes
          clean_workspace: yes
          environment_variables:
            MVN_GOAL: mvn clean install
          jobs:
            build: # name of the job
              resources:
                - nimbus2000
              artifacts:
               - build:
                   source: target
                   destination: build
              tasks:
               - exec: # indicates type of task
                   run_if: passed
                   command: /bin/bash
                   arguments:
                    - -c
                    - $MVN_GOAL
               - plugin:
                   configuration: 
                     id: slack.task 
                     version: 1.3.1
                   options:
                     Channel: gocd
                     Color: 9900cc
                     ColorType: Custom
                     DisplayName: SCM BUILD BOT
                     IconOrEmoji: ":robot_face:"
                     Message: <http://ec2-54-71-67-101.us-west-2.compute.amazonaws.com:8153/go/tab/build/detail/$GO_PIPELINE_NAME/$GO_PIPELINE_COUNTER/$GO_STAGE_NAME/$GO_STAGE_COUNTER/$GO_JOB_NAME|Click here> for details.
                     Title: Happy Happy Joy Joy
                     WebhookUrl: https://hooks.slack.com/services/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
                   run_if: failed
      - Tdawg2.Install: # name of stage
          clean_workspace: true
          jobs:
            install: # name of the job
              resources:
               - nimbus2000
              tasks:
               - fetch: # indicates type of task
                   run_if: passed
                   is_file: no
                   pipeline: Tdawg2
                   stage: Tdawg2.Build
                   job: build
                   source: build/target
                   destination: 
