#tdawg.gocd.yaml
environments:
  testing:
pipelines:
  mypipe1: # definition of mypipe1 pipeline
    group: mygroup # note that the group name can contain only of alphanumeric & underscore characters
    label_template: "${mygit[:8]}"
    locking: off
    materials:
      mygit: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: http://github.com/kevinKalmbach/sovrnTest.git
        branch: master
    stages: # list of stages in order
      - Build: # name of stage
          clean_workspace: true
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: pwd
